### ISSUE TITLE
Contributors ignored during a single evaluation

### ISSUE THREAD

**Issue by iamdanfox** [palantir/policy-bot#63] opened 2019-04-15 10:57 UTC
**Edit:** see [comment](https://github.com/palantir/policy-bot/issues/63#issuecomment-483497069) for a summary of the underlying bug.

----

I left a comment on a single line of this PR (https://github.com/palantir/gradle-conjure/pull/136), but it seems it caused the entire thing to merge.

<img width="863" alt="Screenshot 2019-04-15 at 13 15 10" src="https://user-images.githubusercontent.com/3473798/56131854-87c81480-5f80-11e9-8438-ceefd64be029.png">

Interestingly, the UI seems to still say the PR has not yet been approved, but the status check went green so bulldozer mnerged it.

<img width="800" alt="Screenshot 2019-04-15 at 11 57 15" src="https://user-images.githubusercontent.com/3473798/56127703-aa086500-5f75-11e9-9767-6111c1c92a6a.png">

**Comment by asvoboda** [comment] 2019-04-15 12:12
I think this is a dupe of https://github.com/palantir/policy-bot/issues/52.

**Comment by iamdanfox** [comment] 2019-04-15 12:14
No I actually think this is a separate issue.  I interpret #52 as user confusion that a PR-level comment containing the string `:+1:` results in approving the PR.

My issue here is that a comment _on a single line of a diff_ caused the entire PR to be approved.

**Comment by bluekeyes** [comment] 2019-04-16 03:27
Your comment only triggered an evaluation of the pull request. Review comments (i.e. comments that are part of a review or are attached to a specific line of the diff) are not loaded or considered by policy-bot and the logs confirm that you were not considered as an approver.

What actually happened is that policy-bot did not consider @dansanduleac a contributor for that one evaluation and counted his original approval as fulfilling the `repo owner approval` rule. This is clearly a bug, as future evaluations from the details page show the state as pending.

I will try to figure out what caused this, but it's likely related to the commit loading changes in 1.7.0. That version has already been rolled back to 1.6.1 due to another problem.

**Comment by bluekeyes** [comment] 2019-04-18 21:09
I believe the root cause of this problem is that the new commit loading in 1.7.0 uses the commit count reported as part of the pull request object to know how many commits to list, but `pull_request_review` events (and only these events as far as I can tell) include a partial pull request object that is inexplicably missing this field (despite it appearing in the documentation). That leads us to list zero commits and lose all contributor information.

If the policy used the `invalidate_on_push` option, this would have caused a crash instead, which is the other problem we've been seeing with version 1.7.0.

**Closed as completed** 2019-04-23 00:18 UTC
Labels: bug
