### ISSUE TITLE
Configure maximum depth

### ISSUE THREAD

**Issue by AdamDeHovitz** [palantir/policy-bot#219] opened 2020-08-14 19:00 UTC
Currently policy-bot has a maximum recursive depth of 5 for conjunctions, which our use case has recently superseded. Instead of hard coding it, can the max depth be configurable?

**Comment by bluekeyes** [comment] 2020-08-14 19:08
Closing this as a duplicate of #168. I don't really want to make this configurable yet, but I think doubling the limit is fine (the original value was arbitrary). I'll include that in the next release.

**Closed as completed by bluekeyes** 2020-08-14 19:08 UTC
